name: dashboard
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^13.2.4
  intl: ^0.19.0
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.4
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  firebase_storage: ^11.7.5
  firebase_messaging: ^14.9.2
  cloud_firestore: ^4.17.3
  freezed_annotation: ^2.4.1
  flutter_email_sender: ^6.0.3
  random_string: ^2.3.1
  json_annotation: ^4.9.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true