// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVlTETMqkaQqBGKRi3P2CKoAclp3tSTC8',
    appId: '1:316809988683:web:87a08a541a154a55eb9bce',
    messagingSenderId: '316809988683',
    projectId: 'dashboard-f794a',
    authDomain: 'dashboard-f794a.firebaseapp.com',
    storageBucket: 'dashboard-f794a.appspot.com',
    measurementId: 'G-V0LR1EBWS1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw6Q63W0I0wJmKNin9sa6vR_GilG6SpbY',
    appId: '1:316809988683:android:69ada6c94d6d9189eb9bce',
    messagingSenderId: '316809988683',
    projectId: 'dashboard-f794a',
    storageBucket: 'dashboard-f794a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFZotlF1FAaiwra7tpyqYxu6PmoqWcFHM',
    appId: '1:316809988683:ios:f30622f7f9b7c422eb9bce',
    messagingSenderId: '316809988683',
    projectId: 'dashboard-f794a',
    storageBucket: 'dashboard-f794a.appspot.com',
    iosBundleId: 'com.example.dashboard',
  );

}